import { colorMixVar, colorThemeCssVariables } from './colorThemeStyles'
import { EUCLI_STUDIO_CHAT_ROOT_ID } from '../runtime/eucliStudioGlobals'
import { chatFontFamilyStack, normalizeChatFontSize, normalizeChatLetterSpacing, normalizeChatLineHeight } from '../domain/chatFont'
import type { ColorThemeColors } from '../domain/colorTheme'

export type ChatGlobalStylesParams = {
  colorThemeColors: ColorThemeColors
  transparentChatBg: boolean
  bgAlpha: number
  chatBgBlur: number
  chatFontSize: number
  chatFontFamily: string
  chatLetterSpacing: number
  chatLineHeight: number
}

export function createChatGlobalStyles(params: ChatGlobalStylesParams) {
  const { colorThemeColors, transparentChatBg, bgAlpha, chatBgBlur, chatFontSize, chatFontFamily, chatLetterSpacing, chatLineHeight } = params
  return {
    ':root': {
      ...colorThemeCssVariables(colorThemeColors),
      '--fw-chat-font-size': `${normalizeChatFontSize(chatFontSize)}px`,
      '--fw-chat-font-family': chatFontFamilyStack(chatFontFamily),
      '--fw-chat-letter-spacing': `${normalizeChatLetterSpacing(chatLetterSpacing)}px`,
      '--fw-chat-line-height': String(normalizeChatLineHeight(chatLineHeight)),
      ...(transparentChatBg ? { '--studio-settings-surface': 'transparent', '--studio-settings-surface-shadow': 'none' } : {}),
    },
    'html, body': {
       height: '100%',
       width: '100%',
       overflow: 'hidden',
       overscrollBehavior: 'none',
       color: 'var(--studio-text-primary)',
       background: transparentChatBg ? colorMixVar('--studio-canvas', Math.max(1, bgAlpha * 100)) : 'var(--studio-app-background)',
     },
    [`#${EUCLI_STUDIO_CHAT_ROOT_ID}`]: {
      height: '100%',
      overflow: 'hidden',
      background: transparentChatBg ? colorMixVar('--studio-canvas', Math.max(1, bgAlpha * 100)) : 'var(--studio-app-background)',
      backdropFilter: transparentChatBg && chatBgBlur > 0 ? `blur(${chatBgBlur}px)` : 'none',
      WebkitBackdropFilter: transparentChatBg && chatBgBlur > 0 ? `blur(${chatBgBlur}px)` : 'none',
    },
    '@keyframes fw-tree-pop': {
      '0%': { transform: 'scale(1)' },
      '28%': { transform: 'scale(.92)' },
      '62%': { transform: 'scale(1.07)' },
      '100%': { transform: 'scale(1)' },
    },
    '.fw-tree-node': {
      transformOrigin: 'center',
      transformBox: 'fill-box',
      willChange: 'transform',
    },
    '.fw-tree-node[data-pop="1"]': {
      animation: 'fw-tree-pop 420ms cubic-bezier(.2,.9,.2,1) both',
    },
    '.prose': {
      fontFamily: 'var(--fw-chat-font-family)',
      fontSize: 'var(--fw-chat-font-size)',
      letterSpacing: 'var(--fw-chat-letter-spacing)',
      lineHeight: 'var(--fw-chat-line-height)',
      wordBreak: 'break-word',
      overflowWrap: 'anywhere',
    },
    // 顶层块默认居中：模型常用 max-width 限宽排版，却忘记指定位置，导致整块贴左。
    // 只兜底「模型自己没写位置」的情况——模型写在行内样式的 margin/位置优先级更高，会自动压过本规则。
    // 只作用于顶层直接子级，不碰模型内层的排版。
    '.prose > div': {
      marginLeft: 'auto',
      marginRight: 'auto',
    },
    // fw-chat-text 是「会话界面文字」的统一挂点：用户消息、编辑框、输入框随会话文字设置，
    // 内部输入元素需要显式覆盖（MUI 表单控件的字体来自主题，不随外层继承）。
    [`#${EUCLI_STUDIO_CHAT_ROOT_ID} .fw-chat-text, #${EUCLI_STUDIO_CHAT_ROOT_ID} .fw-chat-text input, #${EUCLI_STUDIO_CHAT_ROOT_ID} .fw-chat-text textarea`]: {
      fontFamily: 'var(--fw-chat-font-family)',
      fontSize: 'var(--fw-chat-font-size)',
      letterSpacing: 'var(--fw-chat-letter-spacing)',
      lineHeight: 'var(--fw-chat-line-height)',
    },
    '.prose pre': {
      overflow: 'auto',
      padding: 12,
      borderRadius: 12,
      background: 'var(--studio-code-background)',
      color: 'var(--studio-code-text)',
      border: '1px solid var(--studio-code-border)',
    },
    '.prose pre.fw-code-block': {
      position: 'relative',
      paddingTop: 38,
      whiteSpace: 'pre-wrap',
      overflowWrap: 'anywhere',
      overflowX: 'hidden',
      overflowY: 'auto',
    },
    '.prose pre.fw-code-block .fw-code-copy': {
      position: 'absolute',
      top: 8,
      right: 8,
      zIndex: 1,
      width: 30,
      height: 30,
      padding: 0,
      borderRadius: 999,
      border: '1px solid var(--studio-code-copy-border)',
      background: 'var(--studio-code-copy-bg)',
      color: 'var(--studio-code-copy-text)',
      fontSize: 12,
      cursor: 'pointer',
      userSelect: 'none',
      WebkitUserSelect: 'none',
      backdropFilter: 'blur(6px)',
      WebkitBackdropFilter: 'blur(6px)',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      '&:hover': { background: 'var(--studio-code-copy-hover)' },
      '&:active': { background: 'var(--studio-code-copy-active)' },
      '&:disabled': { opacity: 0.75, cursor: 'default' },
      '&:focus-visible': { outline: '2px solid var(--studio-code-copy-focus)', outlineOffset: 2 },
    },
    '.prose pre.fw-code-block .fw-code-copy[data-state="ok"], .mermaid-block-action[data-state="ok"]': { color: 'var(--studio-success)' },
    '.prose pre.fw-code-block .fw-code-copy[data-state="fail"], .mermaid-block-action[data-state="fail"]': { color: 'var(--studio-danger)' },
    '.prose code': { fontFamily: 'ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace' },
    '.prose blockquote': {
      margin: '10px 0',
      padding: '8px 12px',
      borderLeft: '4px solid var(--studio-primary)',
      background: 'var(--studio-primary-soft)',
      borderRadius: 12,
    },
    '.prose img': { maxWidth: '100%', height: 'auto' },
    '.prose img.fw-sticker': { maxWidth: 160, maxHeight: 160, width: 'auto', height: 'auto', display: 'inline-block', verticalAlign: 'middle', borderRadius: 12 },
    '.prose .fw-sticker-miss': { color: 'var(--studio-text-secondary)' },
    '.prose table': {
      borderCollapse: 'collapse',
      width: '100%',
      maxWidth: '100%',
      overflowX: 'auto',
      overflowY: 'hidden',
      borderRadius: 12,
      display: 'block',
    },
    '.prose th, .prose td': { border: '1px solid var(--studio-border)', padding: 8, verticalAlign: 'top' },
    '.math-block': { margin: '10px 0', overflowX: 'auto' },
    // KaTeX 的上标/帽子等会超出行盒；inline 公式不要做滚动容器，否则很容易出现裁切或滚动条。
    '.prose .katex, .prose .katex-display': { maxWidth: '100%' },
    '.prose span.katex': { display: 'inline-block', overflow: 'visible', verticalAlign: 'middle' },
     '.prose .katex-display': { overflow: 'visible' },
     '.prose .katex-display > .katex': { display: 'block', overflowX: 'visible' },
    '.fw-math-host': { position: 'relative' },
    '.math-inline.fw-math-host': { display: 'inline-block' },
    '.math-block.fw-math-host': { display: 'block' },
    '.fw-math-copy': {
      position: 'absolute',
      width: 24,
      height: 24,
      padding: 0,
      borderRadius: 999,
      border: '1px solid transparent',
      background: 'transparent',
      color: 'var(--studio-text-secondary)',
      cursor: 'pointer',
      userSelect: 'none',
      WebkitUserSelect: 'none',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: 12,
      lineHeight: 1,
      opacity: 0,
      visibility: 'hidden',
      pointerEvents: 'none',
      transition: 'opacity 120ms ease',
      '&:hover': { background: 'var(--studio-field-hover)', borderColor: 'var(--studio-border)', color: 'var(--studio-text-primary)' },
      '&:active': { background: 'var(--studio-field-focus)', borderColor: 'var(--studio-border)', color: 'var(--studio-text-primary)' },
      '&:focus-visible': { outline: `2px solid ${colorMixVar('--studio-primary', 35)}`, outlineOffset: 2 },
    },
    '.math-inline.fw-math-host > .fw-math-copy': {
      left: '100%',
      top: '50%',
      transform: 'translate(0, -50%)',
    },
    '.math-block.fw-math-host > .fw-math-copy': {
      right: 6,
      top: '50%',
      transform: 'translateY(-50%)',
    },
    '.fw-math-host:hover > .fw-math-copy, .fw-math-host:focus-within > .fw-math-copy': {
      opacity: 1,
      visibility: 'visible',
      pointerEvents: 'auto',
    },
      '.mermaid-block': { margin: '10px 0', overflowX: 'auto', textAlign: 'center' },
      '.mermaid-block[data-mermaid="1"]': { cursor: 'zoom-in' },
       '.mermaid-block svg': { maxWidth: '100%', height: 'auto', display: 'block', margin: '0 auto' },
      '.mermaid-block-ready': {
        position: 'relative',
        borderRadius: 12,
      },
      '.mermaid-block-toolbar': {
        position: 'absolute',
        top: 8,
        right: 8,
        zIndex: 2,
        display: 'inline-flex',
        alignItems: 'center',
        gap: 6,
        opacity: 0,
        visibility: 'hidden',
        pointerEvents: 'none',
        transform: 'translateY(-2px)',
        transition: 'opacity 120ms ease, transform 120ms ease, visibility 120ms ease',
      },
      '.mermaid-block-ready:hover > .mermaid-block-toolbar, .mermaid-block-ready:focus-within > .mermaid-block-toolbar': {
        opacity: 1,
        visibility: 'visible',
        pointerEvents: 'auto',
        transform: 'translateY(0)',
      },
      '.mermaid-block-action': {
        width: 30,
        height: 30,
        padding: 0,
        borderRadius: 999,
        border: '1px solid var(--studio-border)',
        background: 'var(--studio-mermaid-action-bg)',
        color: 'var(--studio-mermaid-action-text)',
        cursor: 'pointer',
        userSelect: 'none',
        WebkitUserSelect: 'none',
        backdropFilter: 'blur(8px)',
        WebkitBackdropFilter: 'blur(8px)',
        boxShadow: 'var(--studio-mermaid-action-shadow)',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        '&:hover': { background: 'var(--studio-mermaid-action-bg-hover)', color: 'var(--studio-mermaid-action-text-hover)' },
        '&:active': { background: 'var(--studio-mermaid-action-bg-hover)' },
        '&:disabled': { opacity: 0.78, cursor: 'default' },
        '&:focus-visible': { outline: `2px solid ${colorMixVar('--studio-primary', 35)}`, outlineOffset: 2 },
      },
     '.mermaid-error': { margin: '10px 0', overflowX: 'auto' },
     '.mermaid-error-box': {
       position: 'relative',
       background: 'var(--studio-mermaid-error-bg)',
       border: '1px solid var(--studio-mermaid-error-border)',
       borderRadius: 12,
       padding: '10px 12px',
       paddingRight: 80,
     },
     '.mermaid-error-fix': {
       position: 'absolute',
       top: 8,
       right: 40,
       width: 28,
       height: 28,
       padding: 0,
       borderRadius: 999,
       border: '1px solid var(--studio-border)',
       background: 'var(--studio-mermaid-error-button-bg)',
       color: 'var(--studio-mermaid-error-button-text)',
       cursor: 'pointer',
       userSelect: 'none',
       WebkitUserSelect: 'none',
       display: 'inline-flex',
       alignItems: 'center',
       justifyContent: 'center',
       '&:hover': { background: 'var(--studio-paper)' },
       '&:active': { background: 'var(--studio-mermaid-error-button-bg)' },
       '&:disabled': { opacity: 0.7, cursor: 'default' },
       '&:focus-visible': { outline: `2px solid ${colorMixVar('--studio-primary', 35)}`, outlineOffset: 2 },
     },
     '.mermaid-error-copy': {
       position: 'absolute',
       top: 8,
       right: 8,
       width: 28,
       height: 28,
       padding: 0,
       borderRadius: 999,
       border: '1px solid var(--studio-border)',
       background: 'var(--studio-mermaid-error-button-bg)',
       color: 'var(--studio-mermaid-error-button-text)',
       cursor: 'pointer',
       userSelect: 'none',
       WebkitUserSelect: 'none',
       display: 'inline-flex',
       alignItems: 'center',
       justifyContent: 'center',
       '&:hover': { background: 'var(--studio-paper)' },
       '&:active': { background: 'var(--studio-mermaid-error-button-bg)' },
       '&:disabled': { opacity: 0.7, cursor: 'default' },
       '&:focus-visible': { outline: `2px solid ${colorMixVar('--studio-primary', 35)}`, outlineOffset: 2 },
     },
     '.mermaid-error-title': { fontWeight: 900, fontSize: 12, color: 'var(--studio-mermaid-error-title)' },
     '.mermaid-error-msg': {
       marginTop: 6,
       fontFamily: 'ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace',
       fontSize: 12,
       color: 'var(--studio-mermaid-error-text)',
       whiteSpace: 'pre-wrap',
       wordBreak: 'break-word',
     },
       '.mermaid-error-src': { display: 'none' },
       '.mermaid-error-err': { display: 'none' },
        '.fw-tool-block': {
          margin: '10px 0',
          borderRadius: 16,
          background: 'var(--studio-tool-block-bg)',
          padding: '10px 12px',
          overflow: 'hidden',
        },
        '.fw-tool-result': {
          background: 'var(--studio-tool-block-bg)',
        },
        '.fw-tool-session': {
          display: 'block',
          margin: '10px 0',
          borderRadius: 18,
          background: 'var(--studio-tool-session-bg)',
          boxShadow: 'var(--studio-tool-session-shadow)',
          overflow: 'hidden',
        },
        '.fw-tool-session-summary': {
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          minWidth: 0,
          padding: '10px 12px',
          cursor: 'pointer',
          userSelect: 'none',
          listStyle: 'none',
        },
        '.fw-tool-session-summary::-webkit-details-marker': { display: 'none' },
        '.fw-tool-session-mark': {
          width: 10,
          height: 28,
          borderRadius: 999,
          background: 'var(--studio-tool-session-mark)',
         flex: '0 0 auto',
       },
        '.fw-tool-session-title': { fontSize: 14, fontWeight: 950, color: 'var(--studio-tool-session-title)' },
        '.fw-tool-session-name': { minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: 12, color: 'var(--studio-tool-session-label)' },
        '.fw-tool-session-pill': {
          borderRadius: 999,
          padding: '1px 8px',
          fontSize: 11,
          color: 'var(--studio-tool-session-label)',
          background: 'var(--studio-tool-session-pill-bg)',
        },
        '.fw-tool-session-spacer': { flex: 1, minWidth: 8 },
        '.fw-tool-session-chevron': {
          width: 18,
          height: 18,
          color: 'var(--studio-tool-session-chevron)',
          transform: 'rotate(0deg)',
          transition: 'transform 160ms ease',
          flex: '0 0 auto',
        },
       '.fw-tool-session-chevron::before': { content: '"⌄"', display: 'block', fontSize: 18, lineHeight: '18px' },
       '.fw-tool-session[open] .fw-tool-session-chevron': { transform: 'rotate(180deg)' },
       '.fw-tool-session-body': { padding: '0 10px 10px' },
       '.fw-tool-session-body .fw-tool-block': { margin: '0 0 8px' },
       '.fw-tool-session-body .fw-tool-block:last-child': { marginBottom: 0 },
      '.fw-tool-header': {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        minWidth: 0,
        marginBottom: 8,
      },
      '.fw-tool-title': {
        display: 'inline-flex',
        alignItems: 'center',
        gap: 8,
        minWidth: 0,
        fontSize: 14,
        fontWeight: 900,
        color: 'var(--studio-tool-session-title)',
      },
       '.fw-tool-glyph': {
         width: 18,
         height: 18,
         borderRadius: 4,
         background: 'var(--studio-tool-glyph-bg)',
         boxShadow: 'none',
         flex: '0 0 auto',
       },
       '.fw-tool-glyph-result': {
         background: 'var(--studio-tool-glyph-result-bg)',
         boxShadow: 'none',
       },
      '.fw-tool-spacer': { flex: 1, minWidth: 8 },
      '.fw-tool-call-id': {
        maxWidth: '50%',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        fontFamily: 'ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace',
        fontSize: 12,
        color: 'var(--studio-tool-call-id)',
        background: 'transparent',
      },
      '.fw-tool-chip-row': {
        display: 'flex',
        flexWrap: 'wrap',
        gap: 8,
        marginBottom: 8,
      },
       '.fw-tool-chip': {
         display: 'inline-flex',
         alignItems: 'center',
         maxWidth: 280,
         minHeight: 24,
         padding: '2px 10px',
         borderRadius: 999,
         background: 'var(--studio-tool-chip-bg)',
         color: 'var(--studio-tool-chip-text)',
         fontSize: 12,
        lineHeight: 1.45,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
      },
       '.fw-tool-chip-success': {
         background: 'var(--studio-success-bg)',
         color: 'var(--studio-success-text)',
         fontWeight: 800,
       },
       '.fw-tool-chip-danger': {
        background: 'var(--studio-danger-bg)',
        color: 'var(--studio-danger-text)',
        fontWeight: 800,
      },
      '.fw-tool-chip-warning': {
        background: 'var(--studio-warning-bg)',
        color: 'var(--studio-warning-text)',
        fontWeight: 800,
      },
      '.fw-tool-field': { marginTop: 8 },
      '.fw-tool-field-label': {
        marginBottom: 4,
        color: 'var(--studio-tool-field-label)',
        fontSize: 12,
        fontWeight: 900,
      },
      '.prose .fw-tool-pre': {
        margin: 0,
        padding: '9px 10px',
        borderRadius: 14,
        background: 'var(--studio-tool-pre-bg)',
        color: 'var(--studio-tool-pre-text)',
        whiteSpace: 'pre-wrap',
        overflowWrap: 'anywhere',
         maxHeight: 260,
         overflow: 'auto',
         fontSize: 12,
         lineHeight: 1.55,
         fontFamily: 'ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace',
       },
      '.prose .fw-tool-pre-raw': {
        background: 'var(--studio-tool-pre-raw-bg)',
      },
      '.prose .fw-tool-pre-live': {
        background: 'var(--studio-tool-pre-live-bg)',
        color: 'var(--studio-tool-pre-live-text)',
      },
      '.fw-tool-meta-line': {
        marginTop: 8,
        fontSize: 12,
        color: 'var(--studio-tool-meta-text)',
      },
      '.fw-tool-diagnostic': {
        margin: '10px 0',
        borderRadius: 16,
        background: 'var(--studio-diagnostic-bg)',
        padding: '10px 12px',
      },
      '.fw-tool-diagnostic-title': {
        fontWeight: 900,
        color: 'var(--studio-diagnostic-title)',
        fontSize: 13,
      },
      '.fw-tool-diagnostic-text': {
        marginTop: 4,
        color: 'var(--studio-diagnostic-text)',
        fontSize: 12,
        lineHeight: 1.6,
      },
  }
}
