import { colorMixVar, colorThemeCssVariables } from './colorThemeStyles'
import { EUCLI_STUDIO_CHAT_ROOT_ID } from '../runtime/eucliStudioGlobals'

export type ChatGlobalStylesParams = {
  colorThemePreset: any
  transparentChatBg: boolean
  bgAlpha: number
  chatBgBlur: number
}

export function createChatGlobalStyles(params: ChatGlobalStylesParams) {
  const { colorThemePreset, transparentChatBg, bgAlpha, chatBgBlur } = params
  return {
    ':root': colorThemeCssVariables(colorThemePreset),
    'html, body': {
       height: '100%',
       width: '100%',
       overflow: 'hidden',
       overscrollBehavior: 'none',
       color: 'var(--studio-text-primary)',
       background: transparentChatBg ? colorMixVar('--studio-canvas', Math.max(1, bgAlpha * 100)) : 'var(--studio-app-background)',
     },
    [`#${EUCLI_STUDIO_CHAT_ROOT_ID}`]: {
      height: '100%',
      overflow: 'hidden',
      background: transparentChatBg ? colorMixVar('--studio-canvas', Math.max(1, bgAlpha * 100)) : 'var(--studio-app-background)',
      backdropFilter: transparentChatBg && chatBgBlur > 0 ? `blur(${chatBgBlur}px)` : 'none',
      WebkitBackdropFilter: transparentChatBg && chatBgBlur > 0 ? `blur(${chatBgBlur}px)` : 'none',
    },
    '@keyframes fw-tree-pop': {
      '0%': { transform: 'scale(1)' },
      '28%': { transform: 'scale(.92)' },
      '62%': { transform: 'scale(1.07)' },
      '100%': { transform: 'scale(1)' },
    },
    '.fw-tree-node': {
      transformOrigin: 'center',
      transformBox: 'fill-box',
      willChange: 'transform',
    },
    '.fw-tree-node[data-pop="1"]': {
      animation: 'fw-tree-pop 420ms cubic-bezier(.2,.9,.2,1) both',
    },
    '.prose': {
      fontSize: 14,
      lineHeight: 1.75,
      wordBreak: 'break-word',
      overflowWrap: 'anywhere',
    },
    '.prose pre': {
      overflow: 'auto',
      padding: 12,
      borderRadius: 12,
      background: 'var(--studio-code-background)',
      color: 'var(--studio-code-text)',
      border: '1px solid rgba(255,255,255,.06)',
    },
    '.prose pre.fw-code-block': {
      position: 'relative',
      paddingTop: 38,
    },
    '.prose pre.fw-code-block .fw-code-copy': {
      position: 'absolute',
      top: 8,
      right: 8,
      zIndex: 1,
      width: 30,
      height: 30,
      padding: 0,
      borderRadius: 999,
      border: '1px solid rgba(255,255,255,.18)',
      background: 'rgba(255,255,255,.08)',
      color: '#e5e7eb',
      fontSize: 12,
      cursor: 'pointer',
      userSelect: 'none',
      WebkitUserSelect: 'none',
      backdropFilter: 'blur(6px)',
      WebkitBackdropFilter: 'blur(6px)',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      '&:hover': { background: 'rgba(255,255,255,.12)' },
      '&:active': { background: 'rgba(255,255,255,.16)' },
      '&:disabled': { opacity: 0.75, cursor: 'default' },
      '&:focus-visible': { outline: '2px solid rgba(255,255,255,.35)', outlineOffset: 2 },
    },
    '.prose pre.fw-code-block .fw-code-copy[data-state="ok"], .mermaid-block-action[data-state="ok"]': { color: '#34d399' },
    '.prose pre.fw-code-block .fw-code-copy[data-state="fail"], .mermaid-block-action[data-state="fail"]': { color: '#f87171' },
    '.prose code': { fontFamily: 'ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace' },
    '.prose blockquote': {
      margin: '10px 0',
      padding: '8px 12px',
      borderLeft: '4px solid var(--studio-primary)',
      background: 'var(--studio-primary-soft)',
      borderRadius: 12,
    },
    '.prose img': { maxWidth: '100%', height: 'auto' },
    '.prose img.fw-sticker': { maxWidth: 160, maxHeight: 160, width: 'auto', height: 'auto', display: 'inline-block', verticalAlign: 'middle', borderRadius: 12 },
    '.prose .fw-sticker-miss': { color: 'rgba(0,0,0,.55)' },
    '.prose table': {
      borderCollapse: 'collapse',
      width: '100%',
      maxWidth: '100%',
      overflowX: 'auto',
      overflowY: 'hidden',
      borderRadius: 12,
      display: 'block',
    },
    '.prose th, .prose td': { border: '1px solid rgba(0,0,0,.12)', padding: 8, verticalAlign: 'top' },
    '.math-block': { margin: '10px 0', overflowX: 'auto' },
    // KaTeX 的上标/帽子等会超出行盒；inline 公式不要做滚动容器，否则很容易出现裁切或滚动条。
    '.prose .katex, .prose .katex-display': { maxWidth: '100%' },
    '.prose span.katex': { display: 'inline-block', overflow: 'visible', verticalAlign: 'middle' },
     '.prose .katex-display': { overflow: 'visible' },
     '.prose .katex-display > .katex': { display: 'block', overflowX: 'visible' },
    '.fw-math-host': { position: 'relative' },
    '.math-inline.fw-math-host': { display: 'inline-block' },
    '.math-block.fw-math-host': { display: 'block' },
    '.fw-math-copy': {
      position: 'absolute',
      width: 24,
      height: 24,
      padding: 0,
      borderRadius: 999,
      border: '1px solid transparent',
      background: 'transparent',
      color: 'rgba(0,0,0,.55)',
      cursor: 'pointer',
      userSelect: 'none',
      WebkitUserSelect: 'none',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: 12,
      lineHeight: 1,
      opacity: 0,
      visibility: 'hidden',
      pointerEvents: 'none',
      transition: 'opacity 120ms ease',
      '&:hover': { background: 'rgba(0,0,0,.06)', borderColor: 'rgba(0,0,0,.12)', color: 'rgba(0,0,0,.72)' },
      '&:active': { background: 'rgba(0,0,0,.10)', borderColor: 'rgba(0,0,0,.12)', color: 'rgba(0,0,0,.76)' },
      '&:focus-visible': { outline: '2px solid rgba(25,118,210,.35)', outlineOffset: 2 },
    },
    '.math-inline.fw-math-host > .fw-math-copy': {
      left: '100%',
      top: '50%',
      transform: 'translate(0, -50%)',
    },
    '.math-block.fw-math-host > .fw-math-copy': {
      right: 6,
      top: '50%',
      transform: 'translateY(-50%)',
    },
    '.fw-math-host:hover > .fw-math-copy, .fw-math-host:focus-within > .fw-math-copy': {
      opacity: 1,
      visibility: 'visible',
      pointerEvents: 'auto',
    },
      '.mermaid-block': { margin: '10px 0', overflowX: 'auto', textAlign: 'center' },
      '.mermaid-block[data-mermaid="1"]': { cursor: 'zoom-in' },
       '.mermaid-block svg': { maxWidth: '100%', height: 'auto', display: 'block', margin: '0 auto' },
      '.mermaid-block-ready': {
        position: 'relative',
        borderRadius: 12,
      },
      '.mermaid-block-toolbar': {
        position: 'absolute',
        top: 8,
        right: 8,
        zIndex: 2,
        display: 'inline-flex',
        alignItems: 'center',
        gap: 6,
        opacity: 0,
        visibility: 'hidden',
        pointerEvents: 'none',
        transform: 'translateY(-2px)',
        transition: 'opacity 120ms ease, transform 120ms ease, visibility 120ms ease',
      },
      '.mermaid-block-ready:hover > .mermaid-block-toolbar, .mermaid-block-ready:focus-within > .mermaid-block-toolbar': {
        opacity: 1,
        visibility: 'visible',
        pointerEvents: 'auto',
        transform: 'translateY(0)',
      },
      '.mermaid-block-action': {
        width: 30,
        height: 30,
        padding: 0,
        borderRadius: 999,
        border: '1px solid rgba(15,23,42,.12)',
        background: 'rgba(255,255,255,.88)',
        color: 'rgba(15,23,42,.72)',
        cursor: 'pointer',
        userSelect: 'none',
        WebkitUserSelect: 'none',
        backdropFilter: 'blur(8px)',
        WebkitBackdropFilter: 'blur(8px)',
        boxShadow: '0 8px 20px rgba(15,23,42,.10)',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        '&:hover': { background: 'rgba(255,255,255,.96)', color: 'rgba(15,23,42,.88)' },
        '&:active': { background: 'rgba(255,255,255,1)' },
        '&:disabled': { opacity: 0.78, cursor: 'default' },
        '&:focus-visible': { outline: '2px solid rgba(25,118,210,.35)', outlineOffset: 2 },
      },
     '.mermaid-error': { margin: '10px 0', overflowX: 'auto' },
     '.mermaid-error-box': {
       position: 'relative',
       background: '#fff',
       border: '1px solid rgba(0,0,0,.12)',
       borderRadius: 12,
       padding: '10px 12px',
       paddingRight: 80,
     },
     '.mermaid-error-fix': {
       position: 'absolute',
       top: 8,
       right: 40,
       width: 28,
       height: 28,
       padding: 0,
       borderRadius: 999,
       border: '1px solid rgba(0,0,0,.12)',
       background: 'rgba(255,255,255,.92)',
       color: 'rgba(0,0,0,.72)',
       cursor: 'pointer',
       userSelect: 'none',
       WebkitUserSelect: 'none',
       display: 'inline-flex',
       alignItems: 'center',
       justifyContent: 'center',
       '&:hover': { background: 'rgba(255,255,255,1)' },
       '&:active': { background: 'rgba(255,255,255,.96)' },
       '&:disabled': { opacity: 0.7, cursor: 'default' },
       '&:focus-visible': { outline: '2px solid rgba(25,118,210,.35)', outlineOffset: 2 },
     },
     '.mermaid-error-copy': {
       position: 'absolute',
       top: 8,
       right: 8,
       width: 28,
       height: 28,
       padding: 0,
       borderRadius: 999,
       border: '1px solid rgba(0,0,0,.12)',
       background: 'rgba(255,255,255,.92)',
       color: 'rgba(0,0,0,.72)',
       cursor: 'pointer',
       userSelect: 'none',
       WebkitUserSelect: 'none',
       display: 'inline-flex',
       alignItems: 'center',
       justifyContent: 'center',
       '&:hover': { background: 'rgba(255,255,255,1)' },
       '&:active': { background: 'rgba(255,255,255,.96)' },
       '&:disabled': { opacity: 0.7, cursor: 'default' },
       '&:focus-visible': { outline: '2px solid rgba(25,118,210,.35)', outlineOffset: 2 },
     },
     '.mermaid-error-title': { fontWeight: 900, fontSize: 12, color: 'rgba(0,0,0,.72)' },
     '.mermaid-error-msg': {
       marginTop: 6,
       fontFamily: 'ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace',
       fontSize: 12,
       color: 'rgba(0,0,0,.82)',
       whiteSpace: 'pre-wrap',
       wordBreak: 'break-word',
     },
      '.mermaid-error-src': { display: 'none' },
      '.mermaid-error-err': { display: 'none' },
       '.fw-tool-block': {
         margin: '10px 0',
         borderRadius: 16,
         background: 'rgba(248,250,252,.92)',
         padding: '10px 12px',
         overflow: 'hidden',
       },
       '.fw-tool-result': {
         background: 'rgba(248,250,252,.92)',
       },
       '.fw-tool-session': {
         display: 'block',
         margin: '10px 0',
         borderRadius: 18,
         background: '#fff',
         boxShadow: '0 8px 24px rgba(15,23,42,.06)',
         overflow: 'hidden',
       },
       '.fw-tool-session-summary': {
         display: 'flex',
         alignItems: 'center',
         gap: 8,
         minWidth: 0,
         padding: '10px 12px',
         cursor: 'pointer',
         userSelect: 'none',
         listStyle: 'none',
       },
       '.fw-tool-session-summary::-webkit-details-marker': { display: 'none' },
       '.fw-tool-session-mark': {
         width: 10,
         height: 28,
         borderRadius: 999,
         background: 'rgba(15,23,42,.18)',
         flex: '0 0 auto',
       },
       '.fw-tool-session-title': { fontSize: 14, fontWeight: 950, color: 'rgba(15,23,42,.92)' },
       '.fw-tool-session-name': { minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: 12, color: 'rgba(15,23,42,.62)' },
       '.fw-tool-session-pill': {
         borderRadius: 999,
         padding: '1px 8px',
         fontSize: 11,
         color: 'rgba(15,23,42,.62)',
         background: 'rgba(15,23,42,.035)',
       },
       '.fw-tool-session-spacer': { flex: 1, minWidth: 8 },
       '.fw-tool-session-chevron': {
         width: 18,
         height: 18,
         color: 'rgba(15,23,42,.54)',
         transform: 'rotate(0deg)',
         transition: 'transform 160ms ease',
         flex: '0 0 auto',
       },
       '.fw-tool-session-chevron::before': { content: '"⌄"', display: 'block', fontSize: 18, lineHeight: '18px' },
       '.fw-tool-session[open] .fw-tool-session-chevron': { transform: 'rotate(180deg)' },
       '.fw-tool-session-body': { padding: '0 10px 10px' },
       '.fw-tool-session-body .fw-tool-block': { margin: '0 0 8px' },
       '.fw-tool-session-body .fw-tool-block:last-child': { marginBottom: 0 },
      '.fw-tool-header': {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        minWidth: 0,
        marginBottom: 8,
      },
      '.fw-tool-title': {
        display: 'inline-flex',
        alignItems: 'center',
        gap: 8,
        minWidth: 0,
        fontSize: 14,
        fontWeight: 900,
        color: 'rgba(15,23,42,.92)',
      },
       '.fw-tool-glyph': {
         width: 18,
         height: 18,
         borderRadius: 4,
         background: 'rgba(15,23,42,.22)',
         boxShadow: 'none',
         flex: '0 0 auto',
       },
       '.fw-tool-glyph-result': {
         background: 'rgba(15,23,42,.32)',
         boxShadow: 'none',
       },
      '.fw-tool-spacer': { flex: 1, minWidth: 8 },
      '.fw-tool-call-id': {
        maxWidth: '50%',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        fontFamily: 'ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace',
        fontSize: 12,
        color: 'rgba(15,23,42,.58)',
        background: 'transparent',
      },
      '.fw-tool-chip-row': {
        display: 'flex',
        flexWrap: 'wrap',
        gap: 8,
        marginBottom: 8,
      },
       '.fw-tool-chip': {
         display: 'inline-flex',
         alignItems: 'center',
         maxWidth: 280,
         minHeight: 24,
         padding: '2px 10px',
         borderRadius: 999,
         background: 'rgba(15,23,42,.055)',
         color: 'rgba(15,23,42,.84)',
         fontSize: 12,
        lineHeight: 1.45,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
      },
       '.fw-tool-chip-success': {
         background: 'rgba(22,163,74,.08)',
         color: '#166534',
         fontWeight: 800,
       },
       '.fw-tool-chip-danger': {
        background: 'rgba(220,38,38,.10)',
        color: '#991b1b',
        fontWeight: 800,
      },
      '.fw-tool-chip-warning': {
        background: 'rgba(217,119,6,.12)',
        color: '#92400e',
        fontWeight: 800,
      },
      '.fw-tool-field': { marginTop: 8 },
      '.fw-tool-field-label': {
        marginBottom: 4,
        color: 'rgba(15,23,42,.62)',
        fontSize: 12,
        fontWeight: 900,
      },
      '.prose .fw-tool-pre': {
        margin: 0,
        padding: '9px 10px',
        borderRadius: 14,
        background: 'rgba(15,23,42,.06)',
        color: 'rgba(15,23,42,.92)',
        whiteSpace: 'pre-wrap',
        overflowWrap: 'anywhere',
         maxHeight: 260,
         overflow: 'auto',
         fontSize: 12,
         lineHeight: 1.55,
         fontFamily: 'ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace',
       },
      '.prose .fw-tool-pre-raw': {
        background: 'rgba(88,28,135,.08)',
      },
      '.prose .fw-tool-pre-live': {
        background: 'rgba(2,132,199,.07)',
        color: 'rgba(12,74,110,.95)',
      },
      '.fw-tool-meta-line': {
        marginTop: 8,
        fontSize: 12,
        color: 'rgba(15,23,42,.62)',
      },
      '.fw-tool-diagnostic': {
        margin: '10px 0',
        borderRadius: 16,
        background: 'rgba(220,38,38,.055)',
        padding: '10px 12px',
      },
      '.fw-tool-diagnostic-title': {
        fontWeight: 900,
        color: '#991b1b',
        fontSize: 13,
      },
      '.fw-tool-diagnostic-text': {
        marginTop: 4,
        color: 'rgba(127,29,29,.82)',
        fontSize: 12,
        lineHeight: 1.6,
      },
  }
}
