export const FOLDER_GRID_ITEM_WIDTH = 116
export const FOLDER_GRID_ITEM_HEIGHT = 132
export const FOLDER_GRID_GAP = 18
export const FOLDER_GRID_PADDING = 16
export const FOLDER_GRID_MIN_HEIGHT = 260
export const FOLDER_GRID_MAX_COORD = 2000

export const FOLDER_GRID_CELL_WIDTH = FOLDER_GRID_ITEM_WIDTH + FOLDER_GRID_GAP
export const FOLDER_GRID_CELL_HEIGHT = FOLDER_GRID_ITEM_HEIGHT + FOLDER_GRID_GAP
