export const FOLDER_GRID_ITEM_WIDTH = 148
export const FOLDER_GRID_ITEM_HEIGHT = 164
export const FOLDER_GRID_GAP = 38
export const FOLDER_GRID_PADDING = 20
export const FOLDER_GRID_MIN_HEIGHT = 260
export const FOLDER_GRID_MAX_COORD = 2000

export const FOLDER_GRID_CELL_WIDTH = FOLDER_GRID_ITEM_WIDTH + FOLDER_GRID_GAP
export const FOLDER_GRID_CELL_HEIGHT = FOLDER_GRID_ITEM_HEIGHT + FOLDER_GRID_GAP
