packages:
  - "."
  - "apps/*"
  - "!apps/ai-draw"
  - "!apps/ai-knowledge-center"
  - "!apps/ai-once"
  - "!apps/ai-studio"
  - "!apps/clipboard-history"
  - "!apps/command-runner"
  - "!apps/everything"
  - "!apps/folders"
  - "!apps/hypercortex"
  - "!apps/language-learning"
  - "!apps/quick-bar"
  - "!apps/task-manager"
  - "!apps/v5-reference-app-go"
  - "!apps/webview"
  - "plugins/*"
