import * as React from 'react'
import { type NoteMeta } from '../core'
import { useTabWorkspaceSidebarActions } from './useTabWorkspaceSidebar'
import { useAppSettingsWritebacks } from './useAppSettings'
import { useDraftOrchestration } from './useDraftOrchestration'
import { useNoteSessions } from './useNoteSessions'
import { useAppCommandDispatch } from './useAppCommandDispatch'
import { useGlobalShortcuts } from './useGlobalShortcuts'
import { useFavoritesWorkspaceActions } from './useFavoritesWorkspace'
import { useNoteInfoUpdate } from './useNoteInfoUpdate'
import { useRepoRestore } from './useRepoRestore'
import { useDeleteGroupAndCloseTabs } from './useDeleteGroupAndCloseTabs'
import type { RepoWorkspaceState } from './useRepoWorkspaceState'

// 动作组合段：工作区与侧边栏动作、应用设置写回、草稿身份编排、笔记会话现场、
// 应用命令分发与全局快捷键、收藏夹动作现场，以及笔记信息更新、仓库恢复、删除分组并关标签
// 三项领域动作（各自成独立子钩子，按依赖顺序在此接线）。
// 状态经 useRepoWorkspaceState 显式入参连接，不引入隐式全局。

export function useRepoWorkspaceActions(state: RepoWorkspaceState) {
  const {
    visible,
    repoId,
    gateway,
    shell,
    settings,
    noteIndex,
    openNoteIds,
    activeNoteId,
    allNotes,
    favoritesDoc,
    workspaces,
    activeWorkspaceId,
    repoReady,
    visiblePage,
    tabsInitReady,
    trashEnabled,
    defaultFaceKinds,
    faceKindOrder,
    shortcutBindingsRef,
    shortcutRecordingRef,
    shortcutHintsOpen,
    tabsMode,
    favoritesSidebarMode,
    currentFolderId,
    favoritesFolderView,
    favoritesNav,
    favoritesNavRef,
    openTabKeysRef,
    activeTabKeyRef,
    favoritesDocRef,
    openNoteIdsRef,
    noteScrollTopByIdRef,
    pageRef,
    sidebarItemsRef,
    tabGroupingRef,
    activeWorkspaceIdRef,
    repoReadyRef,
    closeTabKeysDirectRef,
    activateExistingTabKeyRef,
    updateSidebarItemsRef,
    applyWorkspaceSidebarStateRef,
    activateFavoritesEntryKeyRef,
    commitActiveWorkspacePatchRef,
    resolvedSelectionSourceRef,
    favoritesFolderViewRef,
    openModalPageRef,
    activeNoteIdRef,
    sidebarHoverRef,
    sidebarShortcutHoldRef,
    favoritesHoverRef,
    favoritesSidebarShortcutHoldRef,
    previewHoldRef,
    cancelPreviewClear,
    applyPreviewTarget,
    stopPreview,
    navigatePage,
    recordNewNavLocation,
    goBackPage,
    handleShortcutOpenPage,
    syncNavStackCounts,
    navHistoryRef,
    fwdNavHistoryRef,
    persistRepoStatePatch,
    flushSidebarScrollTop,
    clearSidebarScrollMemory,
    clearFavoritesScrollMemory,
    setDetailSelectionSource,
    setActiveTabKey,
    setActiveNoteId,
    setOpenNoteIds,
    setOpenAssetTabs,
    setNoteIndex,
    setOpenModalPage,
    setShortcutHintsOpen,
    setQuickSearchOpen,
    setTabsHoverOpen,
    setFavoritesHoverOpen,
    setFavoritesActiveScrollSignal,
    setFavoritesActiveFlashSignal,
    setActiveTabScrollSignal,
    setAssetPoolIndex,
    setCurrentFolderId,
    setFavoritesNav,
    setWorkspaces,
    setActiveWorkspaceId,
    setOpenTabKeys,
    setSidebarItems,
    setTabGrouping,
    handleFavoritesDocChange,
    handleUpdateAssetInfo,
    handleOpenAssetTab,
    requestDeleteAssetEntity,
    externalNotesSignal,
  } = state

  const patchAppSettings = shell.patchAppSettings
  const refreshRepos = shell.refreshRepos
  const refreshDataDirStatus = shell.refreshDataDirStatus
  const appCommandQueue = shell.appCommands.queue
  const enqueueAppCommand = shell.appCommands.enqueue
  const consumeAppCommand = shell.appCommands.consume

  // ---- 工作区与侧边栏动作段：装载与持久化能力齐备后接线；工作区切换与新建改名删除、
  // 分组新建折叠改名改色删除、侧边栏条目提交与拖拽移动、工作区现场应用。
  const {
    commitActiveWorkspacePatch,
    updateSidebarItems,
    handleMoveTabToUngroupedIndex,
    handleMoveTabToGroupIndex,
    handleMoveGroupToIndex,
    handleCommitSidebarItems,
    handleSwitchWorkspace,
    handleCreateWorkspace,
    handleRenameWorkspace,
    handleDeleteWorkspace,
    handleCreateTabGroup,
    handleCollapseAllGroups,
    handleAssignTabToGroup,
    handleUnassignTabFromGroup,
    handleToggleGroupCollapsed,
    handleRenameGroup,
    handleSetGroupColor,
    handleDeleteGroupOnly,
  } = useTabWorkspaceSidebarActions({
    gateway,
    workspaces,
    setWorkspaces,
    setActiveWorkspaceId,
    setOpenTabKeys,
    setSidebarItems,
    setTabGrouping,
    setActiveTabKey,
    sidebarItemsRef,
    tabGroupingRef,
    activeWorkspaceIdRef,
    repoReadyRef,
    persistRepoStatePatch,
    flushSidebarScrollTop,
    clearSidebarScrollMemory,
    navigatePage,
    pageRef,
    setDetailSelectionSource,
    setActiveNoteId,
    setOpenNoteIds,
    setOpenAssetTabs,
    commitActiveWorkspacePatchRef,
    updateSidebarItemsRef,
    applyWorkspaceSidebarStateRef,
  })

  const {
    handleShortcutBindingsChange,
    handleShortcutHintsEnabledChange,
    handlePageDisplayModeChange,
    handleColorPresetChange,
    handleRepoCacheLimitChange,
    handleSidebarSortModeChange,
    handleTrashEnabledChange,
    handleTrashAutoDeleteDaysChange,
    handleFacePluginSettingChange,
    handleFaceKindOrderChange,
    handleDefaultFaceKindsChange,
    toggleAllNotesLayout,
    toggleTabsCollapsed,
    toggleTabsMode,
    handleTabsSidebarResizeEnd,
    handleFavoritesSidebarResizeEnd,
    toggleFavoritesSidebarCollapsed,
    toggleFavoritesSidebarMode,
  } = useAppSettingsWritebacks({
    settings,
    patchAppSettings,
    setShortcutHintsOpen,
    setTabsHoverOpen,
    setFavoritesHoverOpen,
    navigatePage,
    syncNavStackCounts,
    navHistoryRef,
    fwdNavHistoryRef,
    pageRef,
    setOpenModalPage,
  })

  // ---- 草稿身份编排：档案与解析派生、草稿登记与打开、左右两侧新建入口、档案变化的左右调和。
  const {
    draftIdentity,
    resolvedNoteIndex,
    openNoteTabs,
    consumeInitSnapshot,
    handleCreateDraftNote,
    handleCreateDraftNoteInFolder,
  } = useDraftOrchestration({
    noteIndex,
    openNoteIds,
    sidebarItemsRef,
    activeTabKeyRef,
    favoritesDocRef,
    tabsInitReady,
    activeWorkspaceIdRef,
    enqueueAppCommand,
    defaultFaceKinds,
    faceKindOrder,
    updateSidebarItems,
    handleFavoritesDocChange,
    navigatePage,
    setOpenNoteIds,
    setActiveNoteId,
    setActiveTabKey,
    setDetailSelectionSource,
  })

  // 常驻键盘回调读取合并后的索引（含草稿），与渲染消费同一份解析结果。
  const noteIndexRef = React.useRef<{ notes?: Record<string, NoteMeta> }>({ notes: resolvedNoteIndex })
  React.useEffect(() => {
    noteIndexRef.current = { notes: resolvedNoteIndex }
  }, [resolvedNoteIndex])

  // ---- 笔记会话现场：会话句柄、打开/关闭与未保存确认、保存/删除/恢复、卡片信息与卡片菜单，收敛到独立模块。
  const {
    noteSessionHandlesRef,
    requestCloseTabRef,
    getNoteSessionRefCallback,
    handleNoteDirtyChange,
    isNoteDirtyById,
    refRelationsEpoch,
    bumpRefRelationsEpoch,
    allNotesById,
    faceSwitchRequest,
    faceSwitchLatestSeq,
    handleFaceSwitchConsumed,
    noteCardInfoById,
    refreshNoteCardInfo,
    ensureNoteCardInfoLoaded,
    noteIndexMap,
    handleOpenNote,
    handleCreateNoteInIndex,
    handleDeleteNote,
    handleTrashRestored,
    closeTabKeysDirect,
    handleCloseAssetTab,
    handleCloseTab,
    handleNoteSessionSaved,
    openNoteCardMenu,
    noteCardMenuNode,
    noteCardDeleteDialog,
    closeTabPromptDialog,
  } = useNoteSessions({
    visible,
    visiblePage,
    gateway,
    activeNoteId,
    faceKindOrder,
    defaultFaceKinds,
    trashEnabled,
    allNotes,
    openNoteTabs,
    favoritesDoc,
    favoritesDocRef,
    handleFavoritesDocChange,
    draftIdentity,
    externalNotesSignal,
    openTabKeysRef,
    activeTabKeyRef,
    pageRef,
    openNoteIdsRef,
    noteScrollTopByIdRef,
    repoReadyRef,
    favoritesFolderViewRef,
    resolvedSelectionSourceRef,
    activateFavoritesEntryKeyRef,
    closeTabKeysDirectRef,
    activateExistingTabKeyRef,
    setDetailSelectionSource,
    setOpenModalPage,
    setOpenNoteIds,
    setActiveNoteId,
    setActiveTabKey,
    setOpenAssetTabs,
    setNoteIndex,
    updateSidebarItems,
    commitActiveWorkspacePatch,
    recordNewNavLocation,
    navigatePage,
    persistRepoStatePatch,
  })

  const handleUpdateNoteInfo = useNoteInfoUpdate({ gateway, setNoteIndex, refreshNoteCardInfo })

  const handleRepoRestored = useRepoRestore({ gateway, refreshRepos })

  useAppCommandDispatch({
    visible,
    tabsInitReady,
    activeWorkspaceId,
    repoReady,
    visiblePage,
    appCommandQueue,
    consumeAppCommand,
    refreshDataDirStatus,
    gateway,
    handleCreateDraftNote,
    navigatePage,
    setShortcutHintsOpen,
    setQuickSearchOpen,
  })

  useGlobalShortcuts({
    visible,
    shortcutBindingsRef,
    shortcutRecordingRef,
    shortcutHintsOpen,
    setShortcutHintsOpen,
    pageRef,
    openModalPageRef,
    activeNoteIdRef,
    activeTabKeyRef,
    openTabKeysRef,
    sidebarItemsRef,
    favoritesFolderViewRef,
    resolvedSelectionSourceRef,
    activateFavoritesEntryKeyRef,
    activateExistingTabKeyRef,
    setFavoritesActiveScrollSignal,
    setActiveTabScrollSignal,
    previewHoldRef,
    cancelPreviewClear,
    applyPreviewTarget,
    stopPreview,
    tabsMode,
    setTabsHoverOpen,
    sidebarShortcutHoldRef,
    sidebarHoverRef,
    toggleTabsCollapsed,
    favoritesSidebarMode,
    setFavoritesHoverOpen,
    favoritesSidebarShortcutHoldRef,
    favoritesHoverRef,
    toggleFavoritesSidebarCollapsed,
    goBackPage,
    handleShortcutOpenPage,
    handleCreateDraftNote,
    setQuickSearchOpen,
    requestCloseTabRef,
    closeTabKeysDirectRef,
    noteSessionHandlesRef,
  })

  // ---- 收藏夹动作现场：浏览位置前进后退与文档调和、当前层导航、实体操作与条目激活，收敛到独立模块。
  const {
    handleNavigateFolder,
    handleDeleteFolderEntity,
    handleCreateFolderInFavorites,
    handleUploadAssetsIntoIndex,
    handleFavoritesSidebarNavigate,
    handleFavoritesSidebarBack,
    handleFavoritesSidebarForward,
    handleFavoritesSidebarContextMenu,
    handleFavoritesSidebarReorder,
    handleFavoritesSidebarMoveRef,
    handleWorkspaceNoteContextMenu,
    handleWorkspaceAssetContextMenu,
    handleCrossColumnDrop,
    handleAddExisting,
    favoritesAddExistingNode,
    favoritesEntityNode,
    workspaceTabEntityNode,
  } = useFavoritesWorkspaceActions({
    gateway,
    repoId,
    trashEnabled,
    favoritesDoc,
    favoritesDocRef,
    handleFavoritesDocChange,
    currentFolderId,
    setCurrentFolderId,
    favoritesNav,
    setFavoritesNav,
    favoritesNavRef,
    persistRepoStatePatch,
    repoReadyRef,
    clearFavoritesScrollMemory,
    setAssetPoolIndex,
    favoritesFolderView,
    favoritesFolderViewRef,
    resolvedNoteIndex,
    noteIndexRef,
    activateFavoritesEntryKeyRef,
    handleOpenNote,
    handleOpenAssetTab,
    handleUpdateNoteInfo,
    handleUpdateAssetInfo,
    handleDeleteNote,
    requestDeleteAssetEntity,
  })

  // 笔记详情「收藏于」标签：把右侧收藏夹栏切到该收藏夹，并把该笔记条目滚入视野并闪烁数次。
  // 导航复用右侧栏统一入口；滚动与闪烁复用其激活条目机制，不新造第二套。
  const handleRevealNoteInFavorites = React.useCallback(
    (folderId: string) => {
      const fid = String(folderId || '').trim()
      if (!fid) return
      handleFavoritesSidebarNavigate(fid)
      setDetailSelectionSource('favorites')
      setFavoritesActiveScrollSignal(signal => signal + 1)
      setFavoritesActiveFlashSignal(signal => signal + 1)
    },
    [handleFavoritesSidebarNavigate, setDetailSelectionSource, setFavoritesActiveFlashSignal, setFavoritesActiveScrollSignal],
  )

  const handleDeleteGroupAndCloseTabs = useDeleteGroupAndCloseTabs({
    sidebarItemsRef,
    handleDeleteGroupOnly,
    closeTabKeysDirect,
  })

  return {
    commitActiveWorkspacePatch,
    updateSidebarItems,
    handleMoveTabToUngroupedIndex,
    handleMoveTabToGroupIndex,
    handleMoveGroupToIndex,
    handleCommitSidebarItems,
    handleSwitchWorkspace,
    handleCreateWorkspace,
    handleRenameWorkspace,
    handleDeleteWorkspace,
    handleCreateTabGroup,
    handleCollapseAllGroups,
    handleAssignTabToGroup,
    handleUnassignTabFromGroup,
    handleToggleGroupCollapsed,
    handleRenameGroup,
    handleSetGroupColor,
    handleDeleteGroupOnly,

    handleShortcutBindingsChange,
    handleShortcutHintsEnabledChange,
    handlePageDisplayModeChange,
    handleColorPresetChange,
    handleRepoCacheLimitChange,
    handleSidebarSortModeChange,
    handleTrashEnabledChange,
    handleTrashAutoDeleteDaysChange,
    handleFacePluginSettingChange,
    handleFaceKindOrderChange,
    handleDefaultFaceKindsChange,
    toggleAllNotesLayout,
    toggleTabsCollapsed,
    toggleTabsMode,
    handleTabsSidebarResizeEnd,
    handleFavoritesSidebarResizeEnd,
    toggleFavoritesSidebarCollapsed,
    toggleFavoritesSidebarMode,

    draftIdentity,
    resolvedNoteIndex,
    openNoteTabs,
    consumeInitSnapshot,
    handleCreateDraftNote,
    handleCreateDraftNoteInFolder,

    noteIndexRef,

    noteSessionHandlesRef,
    requestCloseTabRef,
    getNoteSessionRefCallback,
    handleNoteDirtyChange,
    isNoteDirtyById,
    refRelationsEpoch,
    bumpRefRelationsEpoch,
    allNotesById,
    faceSwitchRequest,
    faceSwitchLatestSeq,
    handleFaceSwitchConsumed,
    noteCardInfoById,
    refreshNoteCardInfo,
    ensureNoteCardInfoLoaded,
    noteIndexMap,
    handleOpenNote,
    handleCreateNoteInIndex,
    handleDeleteNote,
    handleTrashRestored,
    closeTabKeysDirect,
    handleCloseAssetTab,
    handleCloseTab,
    handleNoteSessionSaved,
    openNoteCardMenu,
    noteCardMenuNode,
    noteCardDeleteDialog,
    closeTabPromptDialog,

    handleUpdateNoteInfo,
    handleRepoRestored,

    handleNavigateFolder,
    handleDeleteFolderEntity,
    handleCreateFolderInFavorites,
    handleUploadAssetsIntoIndex,
    handleFavoritesSidebarNavigate,
    handleFavoritesSidebarBack,
    handleFavoritesSidebarForward,
    handleFavoritesSidebarContextMenu,
    handleFavoritesSidebarReorder,
    handleFavoritesSidebarMoveRef,
    handleWorkspaceNoteContextMenu,
    handleWorkspaceAssetContextMenu,
    handleCrossColumnDrop,
    handleAddExisting,
    handleRevealNoteInFavorites,
    favoritesAddExistingNode,
    favoritesEntityNode,
    workspaceTabEntityNode,

    handleDeleteGroupAndCloseTabs,
  }
}

export type RepoWorkspaceActions = ReturnType<typeof useRepoWorkspaceActions>
