export const HyperCortexRpc = {
  notes: {
    loadIndex: 'hypercortex.notes.loadIndex',
    rebuildIndex: 'hypercortex.notes.rebuildIndex',
    listFacePlugins: 'hypercortex.notes.listFacePlugins',
    create: 'hypercortex.notes.create',
    loadManifest: 'hypercortex.notes.loadManifest',
    tryReadManifest: 'hypercortex.notes.tryReadManifest',
    loadFace: 'hypercortex.notes.loadFace',
    saveFaces: 'hypercortex.notes.saveFaces',
    updateMetadata: 'hypercortex.notes.updateMetadata',
    saveFaceOrder: 'hypercortex.notes.saveFaceOrder',
    deleteFace: 'hypercortex.notes.deleteFace',
    saveFaceSettings: 'hypercortex.notes.saveFaceSettings',
    versions: {
      publish: 'hypercortex.notes.versions.publish',
      list: 'hypercortex.notes.versions.list',
      load: 'hypercortex.notes.versions.load',
      restore: 'hypercortex.notes.versions.restore',
    },
  },
  icons: {
    updateNote: 'hypercortex.icons.updateNote',
    updateFolder: 'hypercortex.icons.updateFolder',
    updateAsset: 'hypercortex.icons.updateAsset',
    readImage: 'hypercortex.icons.readImage',
  },
  assets: {
    ensureIndex: 'hypercortex.assets.ensureIndex',
    list: 'hypercortex.assets.list',
    uploadStart: 'hypercortex.assets.upload.start',
    uploadSync: 'hypercortex.assets.upload.sync',
    uploadList: 'hypercortex.assets.upload.list',
    uploadPause: 'hypercortex.assets.upload.pause',
    uploadResume: 'hypercortex.assets.upload.resume',
    uploadCancel: 'hypercortex.assets.upload.cancel',
    readDataUrl: 'hypercortex.assets.readDataUrl',
    delete: 'hypercortex.assets.delete',
    updateMetadata: 'hypercortex.assets.updateMetadata',
    getThumbnail: 'hypercortex.assets.getThumbnail',
    rebuildThumbnail: 'hypercortex.assets.rebuildThumbnail',
    rebuildAllThumbnails: 'hypercortex.assets.rebuildAllThumbnails',
    getVideoThumbnail: 'hypercortex.assets.getVideoThumbnail',
  },
  refs: {
    loadIndex: 'hypercortex.refs.loadIndex',
    queryRelations: 'hypercortex.refs.queryRelations',
  },
  changes: {
    revision: 'hypercortex.changes.revision',
  },
  search: {
    options: 'hypercortex.search.options',
    query: 'hypercortex.search.query',
    queryAssets: 'hypercortex.search.queryAssets',
  },
  repos: {
    list: 'hypercortex.repos.list',
    create: 'hypercortex.repos.create',
    activate: 'hypercortex.repos.activate',
    rename: 'hypercortex.repos.rename',
    delete: 'hypercortex.repos.delete',
    listDeleted: 'hypercortex.repos.listDeleted',
    restore: 'hypercortex.repos.restore',
    purge: 'hypercortex.repos.purge',
  },
  access: {
    load: 'hypercortex.access.load',
    createKey: 'hypercortex.access.createKey',
    updateKey: 'hypercortex.access.updateKey',
    deleteKey: 'hypercortex.access.deleteKey',
    savePort: 'hypercortex.access.savePort',
  },
  metadata: {
    tryLoad: 'hypercortex.metadata.tryLoad',
    ensure: 'hypercortex.metadata.ensure',
    save: 'hypercortex.metadata.save',
  },
  repoState: {
    tryLoad: 'hypercortex.repoState.tryLoad',
    ensure: 'hypercortex.repoState.ensure',
    save: 'hypercortex.repoState.save',
  },
  favorites: {
    tryLoad: 'hypercortex.favorites.tryLoad',
    ensure: 'hypercortex.favorites.ensure',
    createFolder: 'hypercortex.favorites.createFolder',
    updateFolder: 'hypercortex.favorites.updateFolder',
    addItem: 'hypercortex.favorites.addItem',
    removeItem: 'hypercortex.favorites.removeItem',
    moveItem: 'hypercortex.favorites.moveItem',
    reorderItems: 'hypercortex.favorites.reorderItems',
    updateItemLayout: 'hypercortex.favorites.updateItemLayout',
    deleteFolder: 'hypercortex.favorites.deleteFolder',
  },
  trash: {
    list: 'hypercortex.trash.list',
    moveNote: 'hypercortex.trash.moveNote',
    moveAsset: 'hypercortex.trash.moveAsset',
    moveFolder: 'hypercortex.trash.moveFolder',
    permanentlyDeleteNoteDir: 'hypercortex.trash.permanentlyDeleteNoteDir',
    permanentlyDeleteItem: 'hypercortex.trash.permanentlyDeleteItem',
    restore: 'hypercortex.trash.restore',
    maybeAutoCleanup: 'hypercortex.trash.maybeAutoCleanup',
  },
  host: {
    openDir: 'hypercortex.host.openDir',
    openVaultDir: 'hypercortex.host.openVaultDir',
    importLegacyData: 'hypercortex.host.importLegacyData',
  },
} as const
