export const HyperCortexRpc = {
  notes: {
    loadIndex: 'hypercortex.notes.loadIndex',
    rebuildIndex: 'hypercortex.notes.rebuildIndex',
    listFacePlugins: 'hypercortex.notes.listFacePlugins',
    create: 'hypercortex.notes.create',
    loadManifest: 'hypercortex.notes.loadManifest',
    tryReadManifest: 'hypercortex.notes.tryReadManifest',
    loadFace: 'hypercortex.notes.loadFace',
    saveFaces: 'hypercortex.notes.saveFaces',
    saveFaceOrder: 'hypercortex.notes.saveFaceOrder',
    deleteFace: 'hypercortex.notes.deleteFace',
    saveFaceSettings: 'hypercortex.notes.saveFaceSettings',
    versions: {
      publish: 'hypercortex.notes.versions.publish',
      list: 'hypercortex.notes.versions.list',
      load: 'hypercortex.notes.versions.load',
      restore: 'hypercortex.notes.versions.restore',
    },
  },
  assets: {
    ensureIndex: 'hypercortex.assets.ensureIndex',
    list: 'hypercortex.assets.list',
    uploadStart: 'hypercortex.assets.upload.start',
    uploadList: 'hypercortex.assets.upload.list',
    uploadPause: 'hypercortex.assets.upload.pause',
    uploadResume: 'hypercortex.assets.upload.resume',
    uploadCancel: 'hypercortex.assets.upload.cancel',
    readDataUrl: 'hypercortex.assets.readDataUrl',
    delete: 'hypercortex.assets.delete',
    updateMetadata: 'hypercortex.assets.updateMetadata',
    getThumbnail: 'hypercortex.assets.getThumbnail',
    rebuildThumbnail: 'hypercortex.assets.rebuildThumbnail',
    rebuildAllThumbnails: 'hypercortex.assets.rebuildAllThumbnails',
    getVideoThumbnail: 'hypercortex.assets.getVideoThumbnail',
  },
  refs: {
    loadIndex: 'hypercortex.refs.loadIndex',
  },
  search: {
    kinds: 'hypercortex.search.kinds',
    query: 'hypercortex.search.query',
  },
  repos: {
    list: 'hypercortex.repos.list',
    create: 'hypercortex.repos.create',
    activate: 'hypercortex.repos.activate',
  },
  metadata: {
    tryLoad: 'hypercortex.metadata.tryLoad',
    ensure: 'hypercortex.metadata.ensure',
    save: 'hypercortex.metadata.save',
  },
  repoState: {
    tryLoad: 'hypercortex.repoState.tryLoad',
    ensure: 'hypercortex.repoState.ensure',
    save: 'hypercortex.repoState.save',
  },
  favorites: {
    tryLoad: 'hypercortex.favorites.tryLoad',
    ensure: 'hypercortex.favorites.ensure',
    save: 'hypercortex.favorites.save',
  },
  trash: {
    list: 'hypercortex.trash.list',
    moveNote: 'hypercortex.trash.moveNote',
    moveAsset: 'hypercortex.trash.moveAsset',
    permanentlyDeleteNoteDir: 'hypercortex.trash.permanentlyDeleteNoteDir',
    permanentlyDeleteItem: 'hypercortex.trash.permanentlyDeleteItem',
    restore: 'hypercortex.trash.restore',
    maybeAutoCleanup: 'hypercortex.trash.maybeAutoCleanup',
  },
  host: {
    openDir: 'hypercortex.host.openDir',
    openVaultDir: 'hypercortex.host.openVaultDir',
    importLegacyData: 'hypercortex.host.importLegacyData',
  },
} as const
