export const DESKTOP_GRID_ITEM_WIDTH = 148
export const DESKTOP_GRID_ITEM_HEIGHT = 164
export const DESKTOP_GRID_GAP = 38
export const DESKTOP_GRID_PADDING = 20
export const DESKTOP_GRID_MIN_HEIGHT = 260
export const DESKTOP_GRID_MAX_COORD = 2000

export const DESKTOP_GRID_CELL_WIDTH = DESKTOP_GRID_ITEM_WIDTH + DESKTOP_GRID_GAP
export const DESKTOP_GRID_CELL_HEIGHT = DESKTOP_GRID_ITEM_HEIGHT + DESKTOP_GRID_GAP
