import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import {
  bumpV5AppVersion,
  checkV5AppVersion,
} from '../lib/v5-app-versioning.mjs'

async function createFixtureApp(version = '1.2.3') {
  const appDir = await fs.mkdtemp(path.join(os.tmpdir(), 'eucli-studio-versioning-'))
  await fs.mkdir(path.join(appDir, 'src-tauri'), { recursive: true })
  await fs.writeFile(path.join(appDir, 'package.json'), `${JSON.stringify({ name: 'fixture-app', private: true, version }, null, 2)}\n`, 'utf8')
  await fs.writeFile(path.join(appDir, 'src-tauri', 'tauri.conf.json'), `${JSON.stringify({ productName: 'Fixture', version }, null, 2)}\n`, 'utf8')
  await fs.writeFile(path.join(appDir, 'src-tauri', 'tauri.conf.dev.json'), `${JSON.stringify({ productName: 'Fixture Dev', version }, null, 2)}\n`, 'utf8')
  await fs.writeFile(path.join(appDir, 'src-tauri', 'Cargo.toml'), `[package]\nname = "fixture-app"\nversion = "${version}"\nedition = "2021"\n`, 'utf8')
  await fs.writeFile(
    path.join(appDir, 'src-tauri', 'Cargo.lock'),
    `# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "fixture-app"\nversion = "${version}"\n`,
    'utf8',
  )
  await fs.writeFile(
    path.join(appDir, 'release.json'),
    `${JSON.stringify({ version, eucliBoxCompatibility: { minimumVersion: '0.1.0', maximumVersionExclusive: '0.2.0' } }, null, 2)}\n`,
    'utf8',
  )
  return appDir
}

async function removeFixture(appDir) {
  await fs.rm(appDir, { recursive: true, force: true })
}

test('版本一致性检查汇总六处版本目标', async t => {
  const appDir = await createFixtureApp()
  t.after(() => removeFixture(appDir))

  const result = await checkV5AppVersion({ appDir })
  assert.equal(result.currentVersion, '1.2.3')
  assert.equal(result.cargoPackageName, 'fixture-app')
  assert.deepEqual(result.files.map(file => file.version), ['1.2.3', '1.2.3', '1.2.3', '1.2.3', '1.2.3', '1.2.3'])
})

test('版本漂移时拒绝升版', async t => {
  const appDir = await createFixtureApp()
  t.after(() => removeFixture(appDir))
  await fs.writeFile(path.join(appDir, 'src-tauri', 'tauri.conf.json'), `${JSON.stringify({ version: '1.2.2' }, null, 2)}\n`, 'utf8')

  await assert.rejects(() => checkV5AppVersion({ appDir }), /版本漂移/)
  await assert.rejects(() => bumpV5AppVersion({ appDir, bump: 'patch' }), /版本漂移/)
})

test('发布资料版本漂移同样被拦截', async t => {
  const appDir = await createFixtureApp()
  t.after(() => removeFixture(appDir))
  await fs.writeFile(
    path.join(appDir, 'release.json'),
    `${JSON.stringify({ version: '1.2.2', eucliBoxCompatibility: { minimumVersion: '0.1.0', maximumVersionExclusive: '0.2.0' } }, null, 2)}\n`,
    'utf8',
  )

  await assert.rejects(() => checkV5AppVersion({ appDir }), /版本漂移/)
  await assert.rejects(() => bumpV5AppVersion({ appDir, bump: 'patch' }), /版本漂移/)
})

test('dry-run 预演升版但不写盘', async t => {
  const appDir = await createFixtureApp()
  t.after(() => removeFixture(appDir))

  const result = await bumpV5AppVersion({ appDir, bump: 'patch', dryRun: true })
  assert.equal(result.oldVersion, '1.2.3')
  assert.equal(result.newVersion, '1.2.4')
  const after = await checkV5AppVersion({ appDir })
  assert.equal(after.currentVersion, '1.2.3')
})

test('正式升版同步六处版本目标', async t => {
  const appDir = await createFixtureApp()
  t.after(() => removeFixture(appDir))

  const result = await bumpV5AppVersion({ appDir, bump: 'minor' })
  assert.equal(result.newVersion, '1.3.0')
  const after = await checkV5AppVersion({ appDir })
  assert.equal(after.currentVersion, '1.3.0')
  const release = JSON.parse(await fs.readFile(path.join(appDir, 'release.json'), 'utf8'))
  assert.equal(release.version, '1.3.0')
})

test('拒绝无意义升版与非法版本', async t => {
  const appDir = await createFixtureApp()
  t.after(() => removeFixture(appDir))

  await assert.rejects(() => bumpV5AppVersion({ appDir, to: '1.2.3' }), /拒绝无意义升版/)
  await assert.rejects(() => bumpV5AppVersion({ appDir, to: '1.2' }), /x\.y\.z/)
})
